version: '3'
services:
    login_app:
        build: ./darwin_app
        ports:
            - "80:80"
        volumes:
            - .:/code
        depends_on:
            - redis
    redis:
        image: redis